variable "ami_id" {}
variable "environment" {}
variable "instance_type" {}
variable "ssh_cidr" {}
variable "tags" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "db_instance" {}
variable "password" {}